export const PLAYERS = [
  {
    name: "Alice",
    points: 42,
    isActive: false,
    isGK: true,
    isDEF: false,
    isMID: false,
    isST: false,
  },
  {
    name: "Bob",
    points: 67,
    isActive: false,
    isGK: false,
    isDEF: true,
    isMID: false,
    isST: false,
  },
  {
    name: "Charlie",
    points: 18,
    isActive: false,
    isGK: false,
    isDEF: false,
    isMID: false,
    isST: true,
  },
  {
    name: "David",
    points: 93,
    isActive: false,
    isGK: false,
    isDEF: false,
    isMID: false,
    isST: true,
  },
  {
    name: "Eve",
    points: 55,
    isActive: false,
    isGK: false,
    isDEF: true,
    isMID: false,
    isST: false,
  },
  {
    name: "Frank",
    points: 30,
    isActive: false,
    isGK: false,
    isDEF: false,
    isMID: true,
    isST: false,
  },
  {
    name: "Grace",
    points: 82,
    isActive: false,
    isGK: false,
    isDEF: true,
    isMID: false,
    isST: false,
  },
  {
    name: "Hank",
    points: 63,
    isActive: false,
    isGK: false,
    isDEF: false,
    isMID: true,
    isST: false,
  },
  {
    name: "Ivy",
    points: 77,
    isActive: false,
    isGK: false,
    isDEF: false,
    isMID: true,
    isST: false,
  },
  {
    name: "Jack",
    points: 49,
    isActive: false,
    isGK: false,
    isDEF: true,
    isMID: false,
    isST: false,
  },
  {
    name: "naresh",
    points: 49,
    isActive: false,
    isGK: false,
    isDEF: true,
    isMID: false,
    isST: false,
  },
  {
    name: "Ethan",
    points: 42,
    isActive: false,
    isGK: true,
    isDEF: false,
    isMID: false,
    isST: false,
  },
  {
    name: "Diana",
    points: 67,
    isActive: false,
    isGK: false,
    isDEF: true,
    isMID: false,
    isST: false,
  },
  {
    name: "Chris",
    points: 18,
    isActive: false,
    isGK: false,
    isDEF: false,
    isMID: false,
    isST: true,
  },
  {
    name: "Bella",
    points: 93,
    isActive: false,
    isGK: false,
    isDEF: false,
    isMID: false,
    isST: true,
  },
  {
    name: "Aaron",
    points: 55,
    isActive: false,
    isGK: false,
    isDEF: true,
    isMID: false,
    isST: false,
  },
  {
    name: "Zoe",
    points: 30,
    isActive: false,
    isGK: false,
    isDEF: false,
    isMID: true,
    isST: false,
  },
  {
    name: "Yara",
    points: 82,
    isActive: false,
    isGK: false,
    isDEF: true,
    isMID: false,
    isST: false,
  },
  {
    name: "Xander",
    points: 63,
    isActive: false,
    isGK: false,
    isDEF: false,
    isMID: true,
    isST: false,
  },
  {
    name: "Walter",
    points: 77,
    isActive: false,
    isGK: false,
    isDEF: false,
    isMID: true,
    isST: false,
  },
  {
    name: "Violet",
    points: 49,
    isActive: false,
    isGK: false,
    isDEF: true,
    isMID: false,
    isST: false,
  },
  {
    name: "Uma",
    points: 49,
    isActive: false,
    isGK: false,
    isDEF: true,
    isMID: false,
    isST: false,
  },
];
